### ISSUE TITLE
Example of using this in browser?

### ISSUE THREAD

**Issue by Kali95739** [skymen/getOsLocaleCrossPlatform#1]
Can we run this in the script tag as is only thing is require

**Comment by Kali95739** [comment]
I can see with electron but what about nw.js or html? If possible

**Comment by skymen** [comment]
You can include it in the same JS file
https://jsfiddle.net/wahsb259/

or import it as a module
https://codesandbox.io/s/lingering-platform-nj9eo6?file=/src/index.js

nw.js and electron should behave exactly the same in that regard

**Comment by skymen** [comment]
I added a bunch of examples in the project, let me know if that is enough for you

**Comment by Kali95739** [comment]
Bet thank u much appreciated
