### ISSUE TITLE
Child process in the browser

### ISSUE THREAD

**Issue by Kali95739** [skymen/getOsLocaleCrossPlatform#2]
For as child_process goes yea this src is able to use child_process in the browser? If so is it non root only

**Comment by Kali95739** [comment]
Or is the child process only available while running in node? Or electron or nw.js

**Comment by skymen** [comment]
child process does not work in browsers

**Comment by Kali95739** [comment]
Not directly but there has got to be a way to transpile it or etc to make
it work

**Comment by Kali95739** [comment]
Thanks for confirming

**Comment by skymen** [comment]
Why would you ever need this to be in a child process for browsers anyway?
All this does on browsers is call a single function

**Comment by skymen** [comment]
![image](https://user-images.githubusercontent.com/11213825/177078145-3525b6de-e667-4fa7-87f7-4972a893e041.png)

It's just a single value provided by the browsers directly

**Comment by Kali95739** [comment]
It doesnt have to be I was just curious I have a objective I need child
process for

**Comment by Kali95739** [comment]
Ah yes ok
